### ISSUE TITLE
在rails的摸索过程中

### ISSUE THREAD

**Issue by Wellaiyo** [Wellaiyo/meetup#1]
@happypeter rails10日谈看完了，大致上没什么问题　，只是很多你都没细讲　。这个meetup就是结果　，不知道你后面的课程是放在了哪里　，http://happycasts.net/tag/rails　这里吗？　但是好像少了好多期视频

**Comment by happypeter** [comment]
只要跟着能做下来就好了，暂时不必深究原理，后面如果功能做深入了，原理就需要补补了，不然做不下去。后续课程在 http://www.imooc.com/learn/291

后续我的给你的建议是：

- 自己实现一个自己最感兴趣的应用，比如可以把 github 的博客重写一下，增加发博客功能，用户注册然后评论的功能等等，或者就写你的大木头
- 部署项目到真正的 vps 上面
- 没有什么比动手实现自己的想法更有意思的了

**Comment by Wellaiyo** [comment]
![deepinscreenshot20150131150854](https://cloud.githubusercontent.com/assets/10163680/5987218/1d0a7b18-a95b-11e4-8941-dff89f8708e2.png)
怎么会出现这样的编码报错呢？　　我按步骤做到 flash 那一课不知道怎么就这样了

**Comment by happypeter** [comment]
“桌面”这两个字有问题，移动到其他位置把，路径中不要有中文。

**Comment by Wellaiyo** [comment]
老是提示avatar未定义是什么情况　，我对照了代码，没问题呀　
报错了　，我都不知道该怎么去找错误．．．．．
![deepinscreenshot20150131211953](https://cloud.githubusercontent.com/assets/10163680/5988170/487c328a-a98f-11e4-88ee-6c5f9983aea8.png)

**Comment by Wellaiyo** [comment]
我老是觉得我该知道里面的每个词 ，每局代码是什么意思，不然真的好难学明白

**Comment by happypeter** [comment]
@Wellaiyo 对，如果代码都懂那肯定是最好的情况，但是实际情况是不可能做到的，因为知识是海洋，你不可能了解每一个水滴。最聪明的脑袋是最善于把握关键点的脑袋。

那些知识点是最关键的是首先需要掌握的，我自己的经验是这样得知的：

- 自己的勤奋，不断试错，走的弯路多了，自然知道有些内容其实是不重要的，不需要掌握的
- 有老手稍微带一带

**Comment by happypeter** [comment]
像 https://github.com/Wellaiyo/meetup/issues/1#issuecomment-72317578 这个问题，就是很重要很常见的问题，这个是必须要掌握的。

`undefined method 'avatar' for nil class` 的意思并不是 avatar 或者 current_user 没有定义，所以你的代码可能是没有问题的。

原因就是 current_user 现在为空，这个是因为当前没有用户登录进来造成的。

**Comment by Wellaiyo** [comment]
改过来之后确实能点进去issue了，但是还是有两个issue点不进去，同样的错误提示　undefined method 'avatar' for nil class　我是在登陆状态下的，这还可能是什么原因呢

**Comment by happypeter** [comment]
这个我就想不出来了

**Comment by Wellaiyo** [comment]
代码都在仓库里 ，你电脑上有虚拟机么 ，clone运行一下不就知道了 。主页里有两个issue是点不进去的

**Comment by Wellaiyo** [comment]
最近你是在忙着准备imooc的视频吗 ，好期待

**Comment by happypeter** [comment]
@Wellaiyo 我又没有你的数据库，我的主页上怎么会有两个 issue 呢？

这样办，你对照一下代码，代码如果没有问题，那还有一个常见的情况会导致这种情况，那就是数据库中又老数据（也就是字段不全的数据）或者是有依赖性的数据被删除了，比如一个 issue 是 id=1 的 user 创建的，那同时 id=1 的这个 user 已经被删除了，那么这个 issue 就会出问题。

总之，先把数据库重新清空了，然后重新创建试试。

imooc 的 rails技巧库 视频我应该今天就能都录完。

**Comment by Wellaiyo** [comment]
我还有一个想要了解的 ，就是VPS一般你都在哪买 ，我在阿里云见过最便宜的也就55一个月 ，虚拟主机好像要适配Linux系统这样的 ，价格也比较高吧。你有没有相关的建议呢？国外的我不太熟，没意向

**Comment by happypeter** [comment]
rails 技巧库过几天上线的视频中会有这部分的讲解

**Comment by Wellaiyo** [comment]
视频差不多看完了，接下来是要把这个程序从头到尾再研究几遍吗？
对于前端，你有没有好的建议给我

**Comment by happypeter** [comment]
前端你的基础已经可以了，以后随用随练就可以。

现在的思路很简单：

- 自己动手实现一个自己的项目，跟我的 meetup 项目要有一定的差异，但是也不用太难
- 完成到项目上线可以用的程度
- 看看这个过程中有没有什么被卡住的地方

**Comment by Wellaiyo** [comment]
我现在做网站，最大的问题不是说某某效果做不出来，而是没有设计图，不知道该做个什么模样的网站，该有些什么内容。。。。  
>你会不会也有一些这样的问题？

**Comment by happypeter** [comment]
这个就是找几个自己超级喜欢的网站模仿一下就可以了，熟读唐诗三百首，不会吟诗也会揍。

至于该有什么样的内容，这个是根据客户需求来的，不要无病呻吟。

大牛，我觉暂时可以这样，努力保证能够做出一个最简单的东西来就行，暂时不必考虑美观，只要保证跟我的那个 meetup 项目不一样。或者说，就是保证你自己能用 rails 实现自己的想法了，这个先拿下了，再来考虑你说的这个问题我觉得比较合理。

回答你的问题：我没有这样的问题，因为我就是把必要的功能都做出来就不做了。

**Comment by Wellaiyo** [comment]
明白，待我再摸索摸索

**Comment by Wellaiyo** [comment]
@happypeter peter ,happy new year ! 好年要有好运
> 新的一年里，咱们都要有一个新气象

**Comment by happypeter** [comment]
Same 2 u

**Comment by Wellaiyo** [comment]
@happypeter , Can rails do e-commerce sites ?

**Comment by happypeter** [comment]
Sure,  say groupon

**Comment by happypeter** [comment]
also http://knewone.com/

**Comment by Wellaiyo** [comment]
@happypeter 你有没有做过响应式布局的网站 ，我这边急需快速做出响应式布局 ，所以我想找个实例参考一下具体怎么去做 。（现在慢慢摸索着来，速度太慢了~）

**Comment by happypeter** [comment]
惭愧，我这方面经验也比较少。不过非常简单的情况，自己 media-query 一下也是很容易的，或者用 http://www.bootcss.com/ 也很容易实现。

真正复杂的项目，就很难了。事实上，我见过的真正页面稍微复杂点的项目，其实都不是 reponsive 的，而是都是专门为小屏幕设备做另作一个版本。比如 https://www.strikingly.com/ 是 responsive 的，其实他们的页面元素也还是比较少的。

大牛，你有没有见过非常复杂，但是同时又是响应式的网站？

**Comment by happypeter** [comment]
总之，我觉得响应式可能只是个传说，真正差不多的网站做出响应时前端要比做两个版本的网站还要费工夫。

P.S 外行观点，谨慎参考

**Comment by happypeter** [comment]
apple.com 就是两个不同的版本。

另外我的一些网站在手机上浏览也没问题，是因为我把页面宽度设置的足够小。这也是个懒人技巧。

**Comment by happypeter** [comment]
http://www.mi.com/ 更有意思，PC 版网页可以自适应 ipad，但是一旦到了手机上，还是要另起一个版本。

**Comment by Wellaiyo** [comment]
不是吧 ，至少我在windows上面看到的 ，mi.com和apple.com都不是响应式布局呀 。
最近太忙了 ，各种前端的项目要进行 。等过段时间我写好了前端页面再搞rails 配合上去

**Comment by happypeter** [comment]
> mi.com和apple.com都不是响应式布局呀 。

apple.com 是没有的。mi.com 你把浏览器窗口拉窄一点，会看到商品栏原来是一行三个照片的会变成两个

**Comment by Wellaiyo** [comment]
> asserts：js、css、img文件存放的地方。如果把这些文件放在asserts目录，需要额外编译。
> public下建立js、img、css目录是一个好方法。rails以前的版本就是这样处理。
1. js、css、img文件存放在asserts目录下需要额外编译 ，这个编译的具体步骤是什么呢？（或者说是在哪说如哪句代码？）
2. 为什么public下放这些文件也是个好方法？现在的版本又放到asserts目录中？这样编译后的好处是什么呢？
今天看了人家写的rails总结，感觉好多地方不太明白

**Comment by happypeter** [comment]
咱们去访问一个 rails 写的网站，比如要 index.html 或者是 css/main.css ，那么就会去 public 文件夹下去找，有没有 css/main.css 或者是 Index.html ，如果有，那直接就发送给客户端流量器就好了。所以说，把静态 css/js/html 放在 public 下是可以的，但是绝对不是什么“好方法”，只是权宜之计。

但是如果没有，就会去看 routes.rb 中有没有对应的路由规则，然后经过代码运算去生成 html/css 文件。

举一个典型的请求 main.css 的情况为例子。当 rails 处在“开发模式”的时候，如果 public/ 下没有这个文件，就会去 assets/ 下面去找到这个文件，一般是 main.scss 格式，程序会自动进行编译，生成 main.css 。

这样，每次请求都执行编译会比较慢，所以当程序真正部署到服务器上，也就是处于“产品模式”的时候。所有的 .scss .coffee 文件都是已经被 “预先编译” 好，放在 public 目录下的。相应的知识要查看 “assets pipeline" ，部署项目时候需要执行的命令

   rake assets:precomplie



> 这样编译后的好处是什么呢？

好处大大的。第一，可以用更为甜美的语法来写 css/js 了，也就是 sass/coffee 。第二，编译的过程还有哈希处理，能够更好的处理缓存过期。

**Comment by happypeter** [comment]
总结，上面你问的这些问题都是 rails 最基础的知识，任何一本教材或者是官方指南上都有的。http://guides.rubyonrails.org/asset_pipeline.html

**Comment by Wellaiyo** [comment]
@happypeter 
![Uploading image.png . . .]()
