### ISSUE TITLE
诱惑你一下

### ISSUE THREAD

**Issue by happypeter** [Wellaiyo/meetup#2]
https://ruby-china.org/topics/23506

ruby-china 上还有很多招 ruby 的，待遇明显高于其他大部分程序员职位

**Comment by happypeter** [comment]
https://ruby-china.org/topics/12746

**Comment by Wellaiyo** [comment]
好吧 ，你赢了。ruby 就算了 ，rails 倒是可以深入

**Comment by Wellaiyo** [comment]
对了，在http://happypeter.github.io/rails-tricks/10_markdown.html中的gem pygment.rb 应该是gem pygments.rb

**Comment by happypeter** [comment]
感谢，已经改正了。
